locale.load( {
   "id_about": "关于",
   "id_aboutTitle": "关于",
   "id_aboutVer": "版本",
   "id_accept_button": "接受",
   "id_advertisement": "广告",
   "id_and": "和",
   "id_and_accept": "阅读并接受诺基亚的使用条款和隐私条款",
   "id_appName": "热点快报",
   "id_appWelcome": "欢迎",
   "id_clearPersonalData": "清除个人数据",
   "id_clearPersonalDataDesc": "您确定您要清除所有热点快报的数据吗？这将包括您的历史。 ",
   "id_clearPersonalDataTitle": "清除个人数据",
   "id_clearPersonalDataNotification": "清除中...",
   "id_clearPersonalDataSuccessNotification": "个人数据已被清除", // @raghava
   "id_clearPersonalDataFailedNotification": "清除个人数据失败", // @raghava
   "id_errorMsg_exit_Button": "退出",
   "id_errorMsg_settings_button": "设置",
   "id_errorMsg_submit_button": "OK",
   "id_errorMsgConxTimeoutBadData": "当前无法加载改页面，请稍候再试。",
   "id_errorMsgLowMemory": "内存不够。请重启 热点快报 在试一下。",
   "id_errorMsgNoConnection": "没有连接WiFi或移动数据，请检查你的连接设置。",
   "id_errorMsgRetry_button": "重试",
   "id_errorMsgUnknownConxError": "当前无法加载该页面，请检查你的新号和设置。",
   "id_errorMsgUnknownException": "当前无法加载该页面，请稍候再试。",
   "id_filterTile": "Select", // @raghava
   "id_filterName_Filter1": "热点快报",
   "id_filterName_Filter2": "你可能也喜欢",
   "id_filterName_Filter3": "最喜欢的",
   "id_filterName_Filter4": "最新",
   "id_filterHighlightText_Filter2":"热点快报 只对你了解一点 ，进行浏览 并提出宝贵的建议将变的更好。",
   "id_ftuTutorialScreen1Description": "上网浏览能看到跟多的被推荐的故事 也许你也会喜欢。",
   "id_ftuTutorialScreen1Title": "把它变成你的",
   "id_ftuTutorialScreen2Description": "通过分享或喜欢为其他用户突出显示这篇报道。",
   "id_ftuTutorialScreen2Title": "传播爱",
   "id_ftuTutorialScreen3Description": "选择一个类别或者等待看热闻速递",
   "id_fullStory_Button": "详情全文",
   "id_joinUsOnFacebook": "加入我们的Facebook",
   "id_likeStory": "喜欢",
   "id_loading": "加载",
   "id_loadingPageNotification": "更新最新的报道",
   "id_next": "下一页",
   "id_options": "选项",
   "id_pageLoadError": "当前无法加载任何新闻，请稍候再试。",
   "id_previous": "上一页",
   "id_PrivacyPolicy": "隐私条款",
   "id_rateThisApp": "评价这个APP",
   "id_rateThisAppDesc": "您的意见",
   "id_read": "阅读",
   "id_reportAsOffensive": "攻击性报告",
   "id_reset": "清除",
   "id_serviceTerms": "诺基亚使用条款",
   "id_share": "分享",
   "id_storyReported": "取消报告",
   "id_tellUsWhatYouThink": "反馈",
   "id_termsDescA": "热点快报 - 互联网上最容易的沟通方式。",
   "id_termsDescB": "获取被推荐的故事是以你们看到的，喜欢的或者分享 在热点快报 和 Xpress 浏览器上的为基础的。",
   "id_termsDescC": "阅读并接受",
   "id_tryAgain": "再试一次",
   "id_UnlikeStory": "不喜欢",
   "id_ymalFTU": "上网浏览能看到跟多的被推荐的故事 也许你也会喜欢。"
} );